# Generated by Django 3.0.3 on 2020-07-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0003_remove_document_last_change_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_change_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
