# Generated by Django 3.0.3 on 2020-07-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0004_document_last_change_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='signed_file',
            field=models.FileField(blank=True, null=True, upload_to='docs/%Y-%m-%d%/%H-%M-%S/'),
        ),
    ]
