# Generated by Django 3.0.3 on 2020-07-30 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0005_document_signed_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signed_file',
        ),
    ]
